// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/education.tsx";
import * as $1 from "./routes/experience.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/project.tsx";
import * as $4 from "./routes/skill.tsx";
import * as $$0 from "./islands/Contact.tsx";
import * as $$1 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/education.tsx": $0,
    "./routes/experience.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/project.tsx": $3,
    "./routes/skill.tsx": $4,
  },
  islands: {
    "./islands/Contact.tsx": $$0,
    "./islands/NavBar.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
